### ISSUE TITLE
Improve time complexity of the sorting algorithm

### ISSUE THREAD

**Issue by ishanExtreme** [ishanExtreme/Sorting_example#1]
Try to implement sorting using a different technique which is more efficient and fast 🚀🚀🚀🚀
You need to make your PR in [hacktoberfest](https://github.com/ishanExtreme/Sorting_example/tree/hacktoberfest) branch

**Comment by ishika-a** [comment]
Can i take this issue

**Comment by ishanExtreme** [comment]
> Can i take this issue

Yeah sure

**Comment by ishika-a** [comment]
> > Can i take this issue
> 
> Yeah sure

Thank You!
